### ISSUE TITLE
Item frame dupe?

### ISSUE THREAD

**Issue by tomiiiiiiiii** [Ivan8or/GoldenDupes#15]
Not an issue but an idea.

It would be cool to have an item frame dupe (not the piston one) that requires to spam right-click and left-click to dupe the item inside the item frame.

**Comment by Ivan8or** [comment]
Is this a real dupe that existed at some point? If so, can you send a link to a youtube video describing how it works?

**Comment by tomiiiiiiiii** [comment]
> Is this a real dupe that existed at some point? If so, can you send a link to a youtube video describing how it works?

The one that I mentioned is not a real dupe (https://www.youtube.com/watch?v=axUuMuDJ6dg), but there's one that existed back then, which is the piston item frame dupe (https://www.youtube.com/watch?v=pXOncHOAnKw), it would be cool to have at least one of these dupes.

**Comment by Ivan8or** [comment]
i'll consider adding the piston dupe, but I can't give any timeline for it.
