### ISSUE TITLE
Nether Portal Dupe not working on 1.17

### ISSUE THREAD

**Issue by PythonJoshua** [Ivan8or/GoldenDupes#4]
hello, i tried to run this plugin on me and my friends survival server because we wanted to add some sort of temporary dupe, i have set up the nether portal dupe the exact same way as the linked video says to do it, howeveer the chest in minecart doesnt go in the portal, i think paper has its own patch for the dupe which is stopping the minecart from going through

**Comment by PythonJoshua** [comment]
i am on paperspigot

**Comment by sprxll** [comment]
Hi, I'm not a dev or anything, but if you're using illegal stack you'll have to configure it, and also configure your paper.yml Or your spigot.yml

**Comment by PythonJoshua** [comment]
> Hi, I'm not a dev or anything, but if you're using illegal stack you'll have to configure it, and also configure your paper.yml Or your spigot.yml

it was fixed, i think i just had bad timing, i personally dont use illegalstack anyway i dont trust them to much after their older versions having a overpowered dupe lol

**Comment by Ivan8or** [comment]
has this issue been resolved?
