### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ovirse** [Ivan8or/GoldenDupes#5]
28.07 17:31:27 [Server] ERROR Could not pass event PlayerQuitEvent to GoldenDupes v1.3.3
28.07 17:31:27 [Server] INFO java.lang.NullPointerException: null
28.07 17:31:27 [Server] INFO at online.umbcraft.libraries.dupes.DonkeyDupe.clone(DonkeyDupe.java:90) ~[?:?]
28.07 17:31:27 [Server] INFO at online.umbcraft.libraries.dupes.DonkeyDupe.dupeInventory(DonkeyDupe.java:70) ~[?:?]
28.07 17:31:27 [Server] INFO at online.umbcraft.libraries.dupes.DonkeyDupe.traverseBoat(DonkeyDupe.java:60) ~[?:?]
28.07 17:31:27 [Server] INFO at online.umbcraft.libraries.dupes.DonkeyDupe.onPlayerLeave(DonkeyDupe.java:39) ~[?:?]
28.07 17:31:27 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor68.execute(Unknown Source) ~[?:?]
28.07 17:31:27 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-783]
28.07 17:31:27 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-783]
28.07 17:31:27 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-783]
28.07 17:31:27 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-783]
28.07 17:31:27 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerList.disconnect(PlayerList.java:597) ~[patched_1.16.5.jar:git-Paper-783]
28.07 17:31:27 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1856) ~[patched_1.16.5.jar:git-Paper-783]
28.07 17:31:27 [Server] INFO at net.minecraft.server.v1_16_R3.NetworkManager.handleDisconnection(NetworkManager.java:520) ~[patched_1.16.5.jar:git-Paper-783]
28.07 17:31:27 [Server] INFO at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:188) ~[patched_1.16.5.jar:git-Paper-783]
28.07 17:31:27 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1515) ~[patched_1.16.5.jar:git-Paper-783]
28.07 17:31:27 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-783]
28.07 17:31:27 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-783]
28.07 17:31:27 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-783]
28.07 17:31:27 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-783]
28.07 17:31:27 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]

**Comment by ovirse** [comment]
28.07 17:46:48 [Server] ERROR Could not pass event InventoryClickEvent to GoldenDupes v1.3.3
28.07 17:46:48 [Server] INFO java.lang.NullPointerException: null
28.07 17:46:48 [Server] INFO at online.umbcraft.libraries.dupes.NetherPortalDupe.onUseMinecartChest(NetherPortalDupe.java:71) ~[?:?]
28.07 17:46:48 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor69.execute(Unknown Source) ~[?:?]
28.07 17:46:48 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-783]
28.07 17:46:48 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-783]
28.07 17:46:48 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-783]
28.07 17:46:48 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-783]
28.07 17:46:48 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2715) ~[patched_1.16.5.jar:git-Paper-783]
28.07 17:46:48 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Paper-783]
28.07 17:46:48 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-783]
28.07 17:46:48 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-783]

**Comment by Dreeam-qwq** [comment]
same error
https://pastebin.com/pD579GVq
i'm using Purpur 1.17.1 and Java16

**Comment by Ivan8or** [comment]
i'll see if I can get a patch for these out in a day or two
